# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea4447679fb505baa9f9bdd2a273ab216489f10bd61571fd5e8b86e31bbfc7e277d05700aa944accbaf82efafeb69d58224c3b06e49357b2b9b41af035a911f5

test:
  secret_key_base: a7aa90b1da9208da3327726bfd957d21fa3516e0ebd242314c4ce89838e3722689d6b4710e8bbd7e82dda47c9b7e968710d3939ab4fee712c9fa420e76c76f90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
